#Base Stage
FROM node:22.7-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production && \
    npm cache clean --force
COPY tailwind.config.js postcss.config.js ./
COPY . .

#Build Stage
FROM base AS build
RUN npm install && \
    npm run build

#Production Stage
FROM node:22.7-alpine AS production
WORKDIR /app
COPY --from=build /app /app
RUN addgroup appgroup && adduser -S appuser -G appgroup
USER appuser
EXPOSE 80
CMD [ "npm", "start" ]
